Updated Descriptions For Employees
ckcollab/ckcollab pull request #54
Opened 2020-08-24 17:48 UTC by Logan-Ruf

Each current employee description has been added. Format for the description should work well on most screens.

2020-08-24 18:35 UTC, BrendanMyers88 commented
<img width="1439" alt="Screen Shot 2020-08-24 at 11 27 10 AM" src="https://user-images.githubusercontent.com/19380562/91082073-f5686400-e5fc-11ea-9cba-630cf06d1272.png">

Losing some text on Eric, Bailey, Logan, and Nic's profile for a MacBook Screen (1440x756)

2020-08-24 18:38 UTC, Logan-Ruf commented
> <img alt="Screen Shot 2020-08-24 at 11 27 10 AM" width="1439" src="https://user-images.githubusercontent.com/19380562/91082073-f5686400-e5fc-11ea-9cba-630cf06d1272.png">
> 
> Losing some text on Eric, Bailey, Logan, and Nic's profile for a MacBook Screen (1440x756)

That was happening on small screen, but I didn't see it for the larger screens. Should be able to use the "description-sizer" class to make sure the column is the same size as the background.

2020-08-24 18:53 UTC, BrendanMyers88 requested changes
Needs some fixes for inline styling, css values, and I think we should move the data array out of our Vue file and into its own file. Other than that it's looking pretty good. Needs a minor visual fix on a couple lines that are being cut off but other than that great!

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +                                <v-col class="description-sizer" cols="12" md="6" style="text-align: left;">
Can we move this `text-align: left;` out of the component and into the css?

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +                                        <ul style="list-style-type: none">
Pull inline styling and move it to css

```
.skills > ul {
    list-style-type: none;
}

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +                                            <li v-for="skill in slide.skills"><b>{{skill.type}}</b>{{skill.skills}}</li>
```suggestion
                                            <li v-for="skill in slide.skills"><strong>{{skill.type}}</strong>{{skill.skills}}</li>
```
<strong> tag is preferred to <b> tag now.

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +                                <v-col class="description-sizer" style="text-align: left" cols="12" md="6">
Pull inline styling here

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +                                        <template v-if="slide.website != ''">
We can change all these from `v-if="slide.website != ''"` to `v-if="slide.website"` or that equivalent. An empty string evaluates to false so we can just check if there's a string value in our `slide.[link]`

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +                            description: ["Eric started programming at a young age. At the age of 15, he fell in love with it when hacked his school’s school stock exchange. CKC was founded in 2012 s
I'd like to move this slides array out of our HTML and into its own file that we can import so we don't have a massive text dump in the middle of our Vue file.

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +        padding: 0px 20px;
```suggestion
        padding: 0 20px;
```

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +        padding: 0px 20px;
```suggestion
        padding: 0 20px;
```

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +            margin-bottom: 0px;
```suggestion
            margin-bottom: 0;
```

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +            margin-top: 0px;
```suggestion
            margin-top: 0;
```

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +            margin-left: 0px;
```suggestion
            margin-left: 0;
```

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +            margin-right: 0px;
```suggestion
            margin-right: 0;
```

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +            margin-bottom: 0px;
```suggestion
            margin-bottom: 0;
```

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +            margin-top: 0px;
```suggestion
            margin-top: 0;
```

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +            margin-left: 0px;
```suggestion
            margin-left: 0;
```

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +            margin-right: 0px;
```suggestion
            margin-right: 0;
```

2020-08-24 18:53 UTC, BrendanMyers88 commented on about_us.html
> +            background-position-y: -0px;
```suggestion
            background-position-y: 0;
```

2020-08-24 21:47 UTC, BrendanMyers88 commented on about_us.html
> +                            description: ["Eric started programming at a young age. At the age of 15, he fell in love with it when hacked his school’s school stock exchange. CKC was founded in 2012 s
I moved this array in the latest push, make sure you pull from the branch before you re-push

2020-08-27 17:21 UTC, Logan-Ruf commented
Committed changed from review. This should be good to merge.

2020-08-27 17:57 UTC, ckcollab approved these changes

2020-08-27 17:57 UTC, merged